apiVersion: apps/v1
kind: Deployment
metadata:
  name: krampoline
spec:
  selector:
    matchLabels:
      app: krampoline
  template:
    metadata:
      labels:
        app: krampoline
    spec:
      containers:
        - name: krampoline
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_52f90732b72b
          imagePullPolicy: Always
          env:
            - name: JASYPT_ENCRYPTOR_KEY
              valueFrom:
                secretKeyRef:
                  name: krampoline-secret
                  key: jasyptKey
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: krampoline-secret
                  key: databaseUrl
            # 컨테이너 실행 URL 및 포트 설정해주기
            - name: KRAMPOLINE_HOST_URL
              value: "https://fknsp-zpvykljfeg.krampoline.com"
            - name: KRAMPOLINE_HOST_PORT
              value: "80"